config/routes.rb
Rails.application.routes.draw do
  root "shops#index"

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"

  resources :shops, only: [ :index, :new, :create, :destroy, :show ]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/shop.rb
class Shop < ApplicationRecord
    has_many :shop_tags
    has_many :tags, through: :shop_tags

    def self.ransackable_attributes(auth_object = nil)
      [ "closing_time", "holiday", "name", "opening_time" ]
    end

    def self.ransackable_associations(auth_object = nil)
      [ "tags" ]
    end
end

app/models/shop_tag.rb
class ShopTag < ApplicationRecord
  belongs_to :shop
  belongs_to :tag
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :shop_tags
  has_many :shops, through: :shop_tags
  has_many :shop_tags, dependent: :destroy

  def self.ransackable_attributes(auth_object = nil)
    [ "closing_time", "holiday", "name", "opening_time" ]
  end

  def self.ransackable_associations(auth_object = nil)
    [ "closing_time", "holiday", "name", "opening_time" ]
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/shops_controller.rb
class ShopsController < ApplicationController
  def index
    @q = Shop.ransack(params[:q])
    @shops = @q.result(distinct: true)

    if params[:q] && params[:q][:tags_id_eq].present?
        @shops = @shops.joins(:tags).where(tags: { id: params[:q][:tags_id_eq] })
    end
end

def new
    @shop = Shop.new
  end

  def create
    @shop = Shop.new(shop_params)
    if @shop.save
      redirect_to admin_shops_path, notice: "店舗が追加されました"
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @shop.update(shop_params)
      redirect_to admin_shops_path, notice: "店舗情報が更新されました"
    else
      render :edit
    end
  end

  def destroy
    @shop.destroy
    redirect_to admin_shops_path, notice: "店舗が削除されました"
  end

  private

  def set_shop
    @shop = Shop.find(params[:id])
  end

  def shop_params
    params.require(:shop).permit(:name, :opening_time, :closing_time, :holiday, :url) # 必要な属性を追加
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/shops_helper.rb
module ShopsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Myapp" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <!-- <meta name="apple-mobile-web-app-capable" content="yes"> 
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= yield :head %>
    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/shops/_shop_list.erb
<% shops.each do |shop| %>
<div class="col-md-6 mb-3">
  <div class="card">
    <div class="card-body">
      <h3 class="card-title">
        <%= link_to shop.name, shop.url, target: "_blank", class:
        "card-title-link" %>
      </h3>
      <p class="card-text">
        <strong>営業時間:</strong> <%= shop.opening_time.strftime('%H:%M')
        %>〜<%= shop.closing_time.strftime('%H:%M') %><br />
        <strong>定休日:</strong> <%= shop.holiday %><br />
        <strong>タグ:</strong>
        <% shop.tags.each do |tag| %>
        <span class="badge badge-danger"><%= tag.name %></span>
        <% end %>
        <br />
      </p>
    </div>
  </div>
</div>
<% end %>

app/views/shops/index.html.erb
<!DOCTYPE html>
<html lang="ja">
<head>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
  <%= stylesheet_link_tag 'custom', media: 'all', 'data-turbo-track': 'reload' %>
  <%= javascript_include_tag 'application', type: 'module' %>
</head>

<body>
  <h2 class="text-center">梅ヶ枝餅屋さんリスト</h2>

  <div class="container">
    <div class="row mb-3">
      <div class="col-md-6 d-flex align-items-center">
        <%= search_form_for @q, remote: true, html: { id: 'search-form' } do |f| %>
          <div class="d-flex align-items-center">
            <%= f.text_field :name_or_holiday_cont, class: "form-control", placeholder: "あいまい検索" %>
            <%= f.submit "検索", class: "btn btn-primary ml-2" %>
          </div>
        <% end %>
      </div>
      <div class="col-md-6 d-flex align-items-center">
        <%= form_with url: shops_path, method: :get, local: true do %>
          <div class="d-flex align-items-center">
            <%= select_tag 'q[tags_id_eq]', options_from_collection_for_select(Tag.all, :id, :name), prompt: 'タグを選択', class: 'form-control' %>
            <%= submit_tag '検索', class: 'btn btn-primary ml-2' %>
          </div>
        <% end %>
      </div>
    </div>

    <div id="search-results" class="row">
      <%= render partial: 'shop_list', locals: { shops: @shops } %>
    </div>
  </div>
</body>
</html>